### ISSUE TITLE
scroll-to-top button

### ISSUE THREAD

**Issue by Dreezy305** [teacherfund/TeacherFund_next#227] opened 2022-07-24 10:28 UTC
Hi there,

I noticed that the scroll-to-top button on the landing page isn't visible. I'd like to create a scroll-to-top button that will be visible for visitors to see.

I have been working as a front-end developer but I haven't contributed to open source before. I look forward to a response from you

**Comment by joelwass** [comment] 2022-07-24 17:14
Hi @Dreezy305 ! It should be visible once you start scrolling. 

Could you provide a screenshot down a page where it isn't visible?

**Comment by joelwass** [comment] 2022-11-27 21:32
closing as obsolete, i cannot reproduce

**Closed as completed by joelwass** 2022-11-27 21:32 UTC
